apiVersion: v1
kind: Service
metadata:
  name: media-server
  namespace: media
spec:
  selector:
    app: media-server
  ports:
    - name: http
      port: 8081
      targetPort: 8081
  type: ClusterIP