apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: livekit-recordings-pvc
  namespace: livekit
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
  storageClassName: local-path
