apiVersion: v1
kind: Service
metadata:
  name: mysql            # 👈 이 이름이 중요! mysql.database.svc.cluster.local
  namespace: database
spec:
  selector:
    app: mysql
  ports:
    - port: 3306
      targetPort: 3306
  clusterIP: None        # Headless service